/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GNPseudoAleatorios;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;


/**
 *
 * @author Migue
 */
public class AlgoritmoCongruencialCuadratico extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public AlgoritmoCongruencialCuadratico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Semilla = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Generar = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ri = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        xi = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        div = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese la semilla:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        getContentPane().add(Semilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, -1));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese el parámetro a:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 220, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Algoritmo Congruencial Cuadratico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 30));

        Generar.setText("Generar");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });
        jPanel1.add(Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        Clear.setText("Limpiar");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ingrese el parámetro b:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jScrollPane1.setViewportView(ri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, 180));

        jScrollPane2.setViewportView(xi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese el parámetro m:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese el parámetro c:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 220, -1));
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, -1));

        jScrollPane3.setViewportView(div);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GNPseudoAleatorios/Img/a.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GNPseudoAleatorios/Img/a.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 20, 450));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GNPseudoAleatorios/Img/a.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 20, 450));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GNPseudoAleatorios/Img/a.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 640, 20));

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, -1));

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 70, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GNPseudoAleatorios/Img/5.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
        // TODO add your handling code here:
        
        if (evt.getSource()==Generar)
   {    
        
    if(Semilla.getText().equals(""))   //********** Permite verificar si la caja de texto esta vacia **********//
    {
     JOptionPane.showMessageDialog(null,"Ingresa valor de semilla");
    }
    
    if(a.getText().equals(""))
    {
     JOptionPane.showMessageDialog(null,"Ingrese el parámetro a:");
    }
    
    if(c.getText().equals(""))
    {
     JOptionPane.showMessageDialog(null,"Ingrese el parámetro c:");
    }
    if(m.getText().equals(""))
    {
     JOptionPane.showMessageDialog(null,"Ingrese el parámetro m:");
    }
     if(b.getText().equals(""))
    {
     JOptionPane.showMessageDialog(null,"Ingrese el parámetro m:");
    }
        String semilla1=Semilla.getText();
        Integer A= new Integer (a.getText());
        Integer C= new Integer(c.getText());
        Integer M= new Integer(m.getText());
        Integer B= new Integer(b.getText());
      

        String snumero2, snumero3, snumero4, cadenaxi = "",cadenari = "",cadenadiv="";
        int tam1, tam3,  i, primerc, MR ;
        long numero1, numero3, formula;
        int xicuadrado;
        tam1 = semilla1.length();
        numero1 = Integer.parseInt(semilla1);
        MR=M-1;
      
        
        if(numero1<1)
     {
      JOptionPane.showMessageDialog(null,"Valor de la semilla debe ser mayor ó igual a 1");
      Semilla.setText("");
      a.setText("");
      c.setText("");
      m.setText("");
      ri.setText("");
      xi.setText("");
      div.setText("");
      b.setText("");

     }try
     {
        if(numero1>=1){
        for (i=1; i<=M; i++){
             xicuadrado =(int)Math.pow(numero1,2);
             formula = ((A*xicuadrado+B*numero1+C)%M);
             
             snumero2 = Long.toString(formula);
             numero3 = Integer.parseInt(snumero2);
             double rs= (double) numero3/MR;
             BigDecimal formatNumber = new BigDecimal(rs);
             formatNumber = formatNumber.setScale(4, RoundingMode.DOWN);
             
             
            cadenaxi+=("x"+i+ " =  " +snumero2+" \n");
            
            cadenadiv+=(snumero2+"/"+ MR +"\n");
            
            cadenari+=( "r"+i+" = " + formatNumber + " \n");
            
           

           numero1=Integer.parseInt(snumero2);

        }
        xi.setText(cadenaxi);
        ri.setText(cadenari);
        div.setText(cadenadiv);
   }
   
     }catch(java.lang.NumberFormatException e)
     {
      JOptionPane.showMessageDialog(null,"Dato invalido");
      Semilla.setText("");
      a.setText("");
      c.setText("");
      m.setText("");
      ri.setText("");
      xi.setText("");
      div.setText("");
      b.setText("");
     }
   }
    }//GEN-LAST:event_GenerarActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Semilla.setText(null);
        a.setText(null);
        c.setText(null);
        ri.setText(null);
        xi.setText(null);
        div.setText(null);
        m.setText(null);
        b.setText(null);
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Menú Menú = new Menú();
        Menú.setVisible(true);
        AlgoritmoCongruencialCuadratico.this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoCongruencialCuadratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoCongruencialCuadratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoCongruencialCuadratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoCongruencialCuadratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgoritmoCongruencialCuadratico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Generar;
    private javax.swing.JTextField Semilla;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton back;
    private javax.swing.JTextField c;
    private javax.swing.JTextPane div;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField m;
    private javax.swing.JTextPane ri;
    private javax.swing.JTextPane xi;
    // End of variables declaration//GEN-END:variables
}
